name: C/Dart Interoperability Tests
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  at_chops:
    runs-on: ubuntu-latest
    env:
      working-directory: tests/c_dart_interop_tests
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          submodules: true
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1

      - name: get atchops c module
        uses: ./.github/composite/update-submodule
        with:
          module: c/at_c

      # TODO: get dll to build in github actions
      - name: Build C at_chops dll
        working-directory: ${{ env.working-directory }}
        run: |
          cmake -S . -B build
          sudo cmake --build build
  
      - name: get at_chops dart module
        uses: ./.github/composite/update-submodule
        with:
          module: dart/at_libraries
      - name: Dart test
        working-directory: ${{ env.working-directory }}
        run: |
          dart pub get
          dart test

