name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        required: true
        description: The module(s) to update
        options:
          - all
          - at_server
          - at_client_sdk
          - at_libraries
          - at_widgets
          - at_tools
          - at_app

jobs:
  build:
    runs-on: ubuntu-20.04

    outputs:
      commit_ref: ${{ steps.build.outputs.commit_ref }}
      build_id: ${{ steps.build.outputs.build_id }}

    if: ${{ github.repository == 'atsign-foundation/at_mono' }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        id: build
        uses: ./.github/composite/build
        with:
          module: ${{ github.event.inputs.module }}
      
      - name: Bootstrap
        uses: ./.github/composite/melos-bootstrap
        with:
          build_id: ${{ steps.build.outputs.build_id }}

  at_server_tests:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_ref }}
          submodules: recursive

      - name: Retrieve build cache
        uses: ./.github/composite/retrieve-build-cache
        with:
          build_id: ${{ needs.build.outputs.build_id }}

      - name: "Lockfile Sanity Check"
        run: |
          cat ./modules/at_client_sdk/at_client/pubspec.lock | grep -A 6 "at_commons:"
